 - op: add
   path: /metadata/annotations/alb.ingress.kubernetes.io~1group.name
   value: volteryde-shared

 - op: add
   path: /metadata/annotations/alb.ingress.kubernetes.io~1group.order
   value: "20"

 - op: add
   path: /metadata/annotations/alb.ingress.kubernetes.io~1listen-ports
   value: '[{"HTTP": 80}, {"HTTPS":443}]'

 - op: add
   path: /metadata/annotations/alb.ingress.kubernetes.io~1certificate-arn
   value: 'arn:aws:acm:sa-east-1:776127042419:certificate/7b6a8739-4e38-436a-867f-3553fc735a17, arn:aws:acm:sa-east-1:776127042419:certificate/c8ce495c-187b-4e8b-9995-9625d97d068b'

 - op: replace
   path: /spec/rules
   value:
     - host: staging-api.volteryde.com
       http:
         paths:
           - path: /api/v1/telematics
             pathType: Prefix
             backend:
               service:
                 name: volteryde-api
                 port:
                   number: 80
           - path: /api/v1/booking
             pathType: Prefix
             backend:
               service:
                 name: volteryde-api
                 port:
                   number: 80
           - path: /api/v1/fleet
             pathType: Prefix
             backend:
               service:
                 name: volteryde-api
                 port:
                   number: 80
           - path: /api/v1/charging
             pathType: Prefix
             backend:
               service:
                 name: volteryde-api
                 port:
                   number: 80
           - path: /api/v1/route
             pathType: Prefix
             backend:
               service:
                 name: routing-service
                 port:
                   number: 80
           - path: /api/v1/auth
             pathType: Prefix
             backend:
               service:
                 name: volteryde-auth
                 port:
                   number: 80
           - path: /api/v1/payment
             pathType: Prefix
             backend:
               service:
                 name: volteryde-auth
                 port:
                   number: 80
           - path: /api/v1/health
             pathType: Exact
             backend:
               service:
                 name: volteryde-api
                 port:
                   number: 80
